#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"
. "$(dirname "$0")/plainsofpain-bootstrap-shared"

main() {
  info "Running plainsofpain-bootstrap"
  prepareEnshroudedAppFolders
  updateOrCreateEnshroudedServerConfig
  prepareSteamA2sPythonLibrary
  bootstrapHook

  initCrontab
  supervisorctl start plainsofpain-updater
  info "Bootstrap complete"
}

main
